services:
  postgres:
    image: postgres:16
    container_name: postgres-usuario
    environment:
      POSTGRES_DB: agendadorTarefa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendadorTarefa"]
      interval: 5s
      timeout: 5s
      retries: 10

  usuario:
    build: .
    image: usuario:0.0.1-SNAPSHOT
    container_name: usuario-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agendadorTarefa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
